function Hd = highpass
%GETFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
% Generated on: 27-May-2022 17:40:57

Fstop = 12000;     % Stopband Frequency
Fpass = 14000;     % Passband Frequency
Astop = 60;       % Stopband Attenuation (dB)
Apass = 1;        % Passband Ripple (dB)
Fs    = 441000;  % Sampling Frequency

h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);

Hd = design(h, 'equiripple', ...
    'MinOrder', 'any', ...
    'StopbandShape', 'flat');


